name: Bypass review in case of emergency
on:
  pull_request:
    types:
      - labeled
permissions:
  pull-requests: write
jobs:
  approve:
    if: github.event.label.name == 'Emergency Bypass Review'
    uses: bufbuild/base-workflows/.github/workflows/emergency-review-bypass.yaml@3b9e85361ddfb81422eaf6f58b88377a08891953 # main
    secrets: inherit
