name: PR Approval Bypass Notifier
on:
  pull_request:
    types:
      - closed
    branches:
      - main
permissions:
  pull-requests: read
jobs:
  approval:
    uses: bufbuild/base-workflows/.github/workflows/notify-approval-bypass.yaml@3b9e85361ddfb81422eaf6f58b88377a08891953 # main
    secrets: inherit
